### ISSUE TITLE
Location of RaspberryPi directory - does it have to be located under /home/pi ?

### ISSUE THREAD

**Issue by steelewool** [SnoBotics981/RaspberryPi#12]
The vision script file in RaspberryPi/init is looking in /home/pi/Raspberry for files which I've placed in /home/pi/git/RaspberryPi. Is it required that the repository be cloned into /home/pi ? @zcsteele

**Comment by zcsteele** [comment]
That script is designed as more of a template than a drop-in script, since every system is going to be slightly different.  The best solution would be to edit the script after copying it to `/etc/init.d/vision`.

I should probably update the documentation in the script to be more clear.

**Comment by steelewool** [comment]
I wasn't sure if I should in fact be modifying the file. It sounds like I should be just modifying the file to match the directory structure I'm putting things in.

**Comment by steelewool** [comment]
Closing this - since the solution is just to modify the vision script.
