### ISSUE TITLE
How do I change target information

### ISSUE THREAD

**Issue by SnoBotics981** [SnoBotics981/RaspberryPi#8]
Not sure if you have documented this - but I got the software working this evening and I'm wondering if you have that documented somewhere - or could describe it.

**Comment by zcsteele** [comment]
The dashboard utility I put together is accessible at `http://raspberrypi.local:1181/dashboard.html`.  From a windows-based environment, you would need to use the IP address directly instead of `raspberrypi.local`.

I'll add some notes to the readme file for that interface.

**Comment by zcsteele** [comment]
I forgot to mention the runtime configuration tool in the vision software - `http://raspberrypi.local:1181/config`.  That page has several text input fields to set the operating parameters.

...I _really_ need to expand the documentation for the system.

**Comment by steelewool** [comment]
I'll give it a whack after I get past line 17 failing.

**Comment by robSteele-JPL** [comment]
This is working on my Raspberry Pi 3. The zero is having disk/memory issues.
