### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by SnoBotics981** [SnoBotics981/RaspberryPi#9]
FAILURE: Build failed with an exception.

* Where:
Script '/home/pi/git/RaspberryPi/dependencies.gradle' line: 56

* What went wrong:
Execution failed for task ':downloadNtcoreJNI'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not find ntcore-jni-linuxnativearm.jar (edu.wpi.first.ntcore:ntcore-jni:2019.1.1-beta-2).
     Searched in the following locations:
         http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/ntcore/ntcore-jni/2019.1.1-beta-2/ntcore-jni-2019.1.1-beta-2-linuxnativearm.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 5.21 secs

It looks like the .far file has moved. there is now a linuxraspian version of one - but I don't know how to change the build process to reference this file.

The jar files are located in:

http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/ntcore/ntcore-jni/2019.1.1-beta-2/

**Comment by zcsteele** [comment]
The `update-build` branch contains a tweak to change the architecture name used by the frc.wpi.edu repository.  Can you try building that branch and let me know if it works?

**Comment by zcsteele** [comment]
@SnoBotics981 - your reply didn't make it into the conversation tree - but since it's working on your Pi now, I merged that code back to `master`.

**Comment by steelewool** [comment]
I tested the update-build branch before you merged it and it was working great. The camera has been acquiring and displaying images for 10 hours without a burb. Thanks for merging this into the master.
